version: '3.9'

services:

  nginx:
    build: ./nginx
    volumes:
      - static:/var/www/static/
    ports:
      - "80:80"
      - "8000:80"
#      - "443:443"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn great_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/app/static
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    stdin_open: true # for ipdb
    tty: true # for ipdb
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


volumes:
  postgresdata:
  static:
